//
//  PostModels.swift
//  timeline
//
//  Created by pattarapol sawasdee on 13/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Post
{
  // MARK: Use cases

  enum Post
  {
    struct Request
    {
    }
    struct Response
    {
      let data: PresentModel
    }
    struct ViewModel
    {
      let data: PresentModel
    }
  }

  enum FullImage {
    struct Request
    {
      let image: UIImage?
    }
    struct Response
    {
      let image: UIImage?
    }
    struct ViewModel
    {
      let image: UIImage?

    }
  }
}
