//
//  PostPresenter.swift
//  timeline
//
//  Created by pattarapol sawasdee on 13/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPresentationLogic
{
  func presentSomething(response: Post.Something.Response)
}

class PostPresenter: PostPresentationLogic
{
  weak var viewController: PostDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Post.Something.Response)
  {
    let viewModel = Post.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
