//
//  PostInteractor.swift
//  timeline
//
//  Created by pattarapol sawasdee on 13/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic
{
  func getPost(request: Post.Post.Request)
  func getFullImage(request: Post.FullImage.Request)
}

protocol PostDataStore
{
  //var name: String { get set }
  var title: String { get set }
  var photoList: [String]? { get set }

}

class PostInteractor: PostBusinessLogic, PostDataStore
{
  var presenter: PostPresentationLogic?
  var worker: PostWorker?
  var title: String = ""
  var photoList: [String]?
  //var name: String = ""
  
  // MARK: Do something
  
  func getPost(request: Post.Post.Request)
  {
    let response = Post.Post.Response(title: title, photoList: photoList ?? [])
    presenter?.presentPost(response: response)
  }

  func getFullImage(request: Post.FullImage.Request) {
    let response = Post.FullImage.Response(imageUrl: photoList?[safe: request.index] ?? "")
    presenter?.presentFullImage(response: response)
  }
}
