//
//  FeedWorker.swift
//  timeline
//
//  Created by pattarapol sawasdee on 12/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FeedWorker
{

  func getAlbums(success: @escaping (Albums) -> Void, error: @escaping (Error)  -> Void) {
    _ = WebService(host: .Gorest).request(AlbumsRequest()) { result in
      switch result {
      case .success(let data):
        success(data)
      case .failure(let err):
        error(err)
      }
    }
  }

  func getPhoto(albumId: String, success: @escaping (Photos) -> Void, error: @escaping (Error)  -> Void) {
    _ = WebService(host: .Gorest).request(PhotosRequest(albumId: albumId)) { result in
      switch result {
      case .success(let data):
        success(data)
      case .failure(let err):
        error(err)
      }
    }
  }
}
