//
//  FeedModels.swift
//  timeline
//
//  Created by pattarapol sawasdee on 12/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Feed
{
  // MARK: Use cases

  enum AlbumFeed {
    struct Request
    {
    }
    struct Response
    {
      let albums: Albums
    }
    struct ViewModel
    {
      let data: [PresentFeed]
    }
  }

  enum Photo
  {
    struct Request
    {
      let id: String
      let indexPath: IndexPath
    }
    struct Response
    {
      let id: String
      let photo: Photos
      let indexPath: IndexPath
    }
    struct ViewModel
    {
      let id: String
      let photoList: [String]
      let indexPath: IndexPath
    }
  }

  enum Post
  {
    struct Request
    {
      let id: String
      let time: String
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }

  struct PresentFeed {
    let id, title: String
    var photoList: [String]?
    var isLoadPhoto: Bool = false
  }
}
