//
//  FeedPresenter.swift
//  timeline
//
//  Created by pattarapol sawasdee on 12/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedPresentationLogic
{
  func presentFeed(response: Feed.AlbumFeed.Response)
  func presentPhoto(response: Feed.Photo.Response)
  func presentPostView(response: Feed.Post.Response)
}

class FeedPresenter: FeedPresentationLogic
{
  weak var viewController: FeedDisplayLogic?
  
  // MARK: Do something

  func presentFeed(response: Feed.AlbumFeed.Response) {

    let presentFeedData = response.albums.result.map { item -> Feed.PresentFeed in
      return Feed.PresentFeed(id: item.id, title: item.title)
    }
    let viewModel = Feed.AlbumFeed.ViewModel(data: presentFeedData)
    viewController?.displayFeed(viewModel: viewModel)
  }

  func presentPhoto(response: Feed.Photo.Response) {

    var photos: [String] = []
    response.photo.result.forEach { item in
      if photos.count == 3 { return }
      photos.append(item.url)
    }

    let viewModel = Feed.Photo.ViewModel(id: response.id, photoList: photos, indexPath: response.indexPath)
    viewController?.displayPhoto(viewModel: viewModel)
  }

  func presentPostView(response: Feed.Post.Response) {
    viewController?.routeToPost(viewModel: Feed.Post.ViewModel())
  }
  
}
