//
//  NewPostPresenter.swift
//  timeline
//
//  Created by pattarapol sawasdee on 14/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostPresentationLogic
{
  func presentNewPost(response: NewPost.NewPost.Response)
}

class NewPostPresenter: NewPostPresentationLogic
{
  weak var viewController: NewPostDisplayLogic?
  
  // MARK: Do something
  
  func presentNewPost(response: NewPost.NewPost.Response)
  {
    let viewModel = NewPost.NewPost.ViewModel()
    viewController?.routeToParent(viewModel: viewModel)
  }
}
