//
//  NewPostInteractor.swift
//  timeline
//
//  Created by pattarapol sawasdee on 14/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostBusinessLogic
{
  func setNewPost(request: NewPost.NewPost.Request)
}

protocol NewPostDataStore
{
  var text: String { get set }
  var image1: UIImage? { get set }
  var image2: UIImage? { get set }
  var image3: UIImage? { get set }
}

class NewPostInteractor: NewPostBusinessLogic, NewPostDataStore
{
  var presenter: NewPostPresentationLogic?
  var worker: NewPostWorker?
  var text: String = ""
  var image1: UIImage?
  var image2: UIImage?
  var image3: UIImage?
  
  // MARK: Do something

  func setNewPost(request: NewPost.NewPost.Request) {
    text = request.text
    image1 = request.image1
    image2 = request.image2
    image3 = request.image3
    presenter?.presentNewPost(response: NewPost.NewPost.Response())
  }
}
