//
//  NewPostWorker.swift
//  timeline
//
//  Created by pattarapol sawasdee on 14/10/2562 BE.
//  Copyright (c) 2562 pattarapol. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewPostWorker
{
  func doSomeWork()
  {
  }
}
